/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 28/11/2025 02:50:29
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

#define MX_DEVICE_VERSION                  0x01000000U

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     168000000
#define MX_SYSCLKFreq_VALUE                     168000000
#define MX_HCLKFreq_Value                       168000000
#define MX_FCLKCortexFreq_Value                 168000000
#define MX_CortexFreq_Value                     168000000
#define MX_AHBFreq_Value                        168000000
#define MX_APB1Freq_Value                       42000000
#define MX_APB2Freq_Value                       84000000
#define MX_APB1TimFreq_Value                    84000000
#define MX_APB2TimFreq_Value                    168000000
#define MX_48MHZClocksFreq_Value                84000000
#define MX_EthernetFreq_Value                   168000000
#define MX_I2SClocksFreq_Value                  96000000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    168000000

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1
#define MX_I2C1_PERIPH_CLOCK_FREQ               42000000   

/* GPIO Configuration */

/* Pin PB8 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SCL_Pin                         PB8
#define MX_I2C1_SCL_GPIOx                       GPIOB
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_8
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SCL_GPIO_PuPd                   GPIO_NOPULL
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB9 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_I2C1_SDA_Pin                         PB9
#define MX_I2C1_SDA_GPIOx                       GPIOB
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_9
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SDA_GPIO_PuPd                   GPIO_NOPULL
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/* NVIC Configuration */

/* NVIC I2C1_EV_IRQn */
#define MX_I2C1_EV_IRQn_interruptPremptionPriority 0
#define MX_I2C1_EV_IRQn_PriorityGroup           NVIC_PRIORITYGROUP_4
#define MX_I2C1_EV_IRQn_Subriority              0

/* NVIC I2C1_ER_IRQn */
#define MX_I2C1_ER_IRQn_interruptPremptionPriority 0
#define MX_I2C1_ER_IRQn_PriorityGroup           NVIC_PRIORITYGROUP_4
#define MX_I2C1_ER_IRQn_Subriority              0

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PF6 */
#define MX_PF6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF6_Pin                              PF6
#define MX_PF6_GPIOx                            GPIOF
#define MX_PF6_PinState                         GPIO_PIN_RESET
#define MX_PF6_GPIO_PuPd                        GPIO_NOPULL
#define MX_PF6_GPIO_Pin                         GPIO_PIN_6
#define MX_PF6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PF9 */
#define MX_PF9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF9_Pin                              PF9
#define MX_PF9_GPIOx                            GPIOF
#define MX_PF9_PinState                         GPIO_PIN_RESET
#define MX_PF9_GPIO_PuPd                        GPIO_NOPULL
#define MX_PF9_GPIO_Pin                         GPIO_PIN_9
#define MX_PF9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PF8 */
#define MX_PF8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF8_Pin                              PF8
#define MX_PF8_GPIOx                            GPIOF
#define MX_PF8_PinState                         GPIO_PIN_RESET
#define MX_PF8_GPIO_PuPd                        GPIO_NOPULL
#define MX_PF8_GPIO_Pin                         GPIO_PIN_8
#define MX_PF8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PF1 */
#define MX_PF1_Pin                              PF1
#define MX_PF1_GPIOx                            GPIOF
#define MX_PF1_GPIO_PuPd                        GPIO_NOPULL
#define MX_PF1_GPIO_Pin                         GPIO_PIN_1
#define MX_PF1_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PF3 */
#define MX_PF3_Pin                              PF3
#define MX_PF3_GPIOx                            GPIOF
#define MX_PF3_GPIO_PuPd                        GPIO_NOPULL
#define MX_PF3_GPIO_Pin                         GPIO_PIN_3
#define MX_PF3_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PF2 */
#define MX_PF2_Pin                              PF2
#define MX_PF2_GPIOx                            GPIOF
#define MX_PF2_GPIO_PuPd                        GPIO_NOPULL
#define MX_PF2_GPIO_Pin                         GPIO_PIN_2
#define MX_PF2_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PF5 */
#define MX_PF5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF5_Pin                              PF5
#define MX_PF5_GPIOx                            GPIOF
#define MX_PF5_PinState                         GPIO_PIN_RESET
#define MX_PF5_GPIO_PuPd                        GPIO_NOPULL
#define MX_PF5_GPIO_Pin                         GPIO_PIN_5
#define MX_PF5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PF4 */
#define MX_PF4_Pin                              PF4
#define MX_PF4_GPIOx                            GPIOF
#define MX_PF4_GPIO_PuPd                        GPIO_NOPULL
#define MX_PF4_GPIO_Pin                         GPIO_PIN_4
#define MX_PF4_GPIO_Mode                        GPIO_MODE_INPUT

#endif  /* __MX_DEVICE_H */

